name: gomiland
description: "Recycling game"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bonfire: ^3.2.0
  flame: ^1.14.0
  flame_audio: ^2.1.7
  flame_splash_screen: ^0.2.0
  provider: ^6.1.1

dev_dependencies:
  assets_gen: ^1.5.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/bgm/
    - assets/audio/sfx/
    - assets/images/npcs/
    - assets/images/npcs/monk/
    - assets/images/buildings/
    - assets/images/spritesheets/
    - assets/images/logo/
    - assets/images/player/
    - assets/images/tiles/

  fonts:
    - family: minecraft
      fonts:
        - asset: fonts/minecraft.ttf

