name: gomiland
description: "Recycling game"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.14.0
  flame_audio: ^2.1.7
  flame_splash_screen: ^0.2.0
  provider: ^6.1.1
  flame_tiled: ^1.18.3
  flame_bloc: ^1.10.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  animated_text_kit: ^4.2.2
  jenny: ^1.2.1
  collection: ^1.18.0
  flame_tiled_utils: ^1.1.1

dev_dependencies:
  assets_gen: ^1.5.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tiles/
    - assets/audio/bgm/
    - assets/audio/sfx/
    - assets/images/
    - assets/images/trees/
    - assets/images/ui/
    - assets/images/npcs/
    - assets/images/buildings/
    - assets/images/spritesheets/
    - assets/images/logo/
    - assets/images/player/
    - assets/images/objects/
    - assets/images/rubbish/
    - assets/images/tile_maps/
    - assets/yarn/

  fonts:
    - family: minecraft
      fonts:
        - asset: fonts/minecraft.ttf

