// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 40.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'gomiland';

  static const String assets_audio_bgm_mountain_diary_mp3 = 'assets/audio/bgm/mountain_diary.mp3';
  static const String gomiland$assets_audio_bgm_mountain_diary_mp3 = 'packages/gomiland/assets/audio/bgm/mountain_diary.mp3';

  static const String assets_audio_bgm_olib_oil_mp3 = 'assets/audio/bgm/olib_oil.mp3';
  static const String gomiland$assets_audio_bgm_olib_oil_mp3 = 'packages/gomiland/assets/audio/bgm/olib_oil.mp3';

  static const String assets_audio_bgm_roomboi_mp3 = 'assets/audio/bgm/roomboi.mp3';
  static const String gomiland$assets_audio_bgm_roomboi_mp3 = 'packages/gomiland/assets/audio/bgm/roomboi.mp3';

  static const String assets_audio_bgm_scenic_stroll_mp3 = 'assets/audio/bgm/scenic_stroll.mp3';
  static const String gomiland$assets_audio_bgm_scenic_stroll_mp3 = 'packages/gomiland/assets/audio/bgm/scenic_stroll.mp3';

  static const String assets_audio_bgm_wumwob_squarewave_mp3 = 'assets/audio/bgm/wumwob_squarewave.mp3';
  static const String gomiland$assets_audio_bgm_wumwob_squarewave_mp3 = 'packages/gomiland/assets/audio/bgm/wumwob_squarewave.mp3';

  static const String assets_audio_sfx_correct_mp3 = 'assets/audio/sfx/correct.mp3';
  static const String gomiland$assets_audio_sfx_correct_mp3 = 'packages/gomiland/assets/audio/sfx/correct.mp3';

  static const String assets_audio_sfx_incorrect_mp3 = 'assets/audio/sfx/incorrect.mp3';
  static const String gomiland$assets_audio_sfx_incorrect_mp3 = 'packages/gomiland/assets/audio/sfx/incorrect.mp3';

  static const String assets_audio_sfx_next_mp3 = 'assets/audio/sfx/next.mp3';
  static const String gomiland$assets_audio_sfx_next_mp3 = 'packages/gomiland/assets/audio/sfx/next.mp3';

  static const String assets_audio_sfx_pickup_mp3 = 'assets/audio/sfx/pickup.mp3';
  static const String gomiland$assets_audio_sfx_pickup_mp3 = 'packages/gomiland/assets/audio/sfx/pickup.mp3';

  static const String assets_images_buildings_entrance_png = 'assets/images/buildings/entrance.png';
  static const String gomiland$assets_images_buildings_entrance_png = 'packages/gomiland/assets/images/buildings/entrance.png';

  static const String assets_images_buildings_home_png = 'assets/images/buildings/home.png';
  static const String gomiland$assets_images_buildings_home_png = 'packages/gomiland/assets/images/buildings/home.png';

  static const String assets_images_logo_gomiland_simple_png = 'assets/images/logo/gomiland_simple.png';
  static const String gomiland$assets_images_logo_gomiland_simple_png = 'packages/gomiland/assets/images/logo/gomiland_simple.png';

  static const String assets_images_npcs_monk_idle_down_png = 'assets/images/npcs/monk/idle_down.png';
  static const String gomiland$assets_images_npcs_monk_idle_down_png = 'packages/gomiland/assets/images/npcs/monk/idle_down.png';

  static const String assets_images_npcs_monk_idle_left_png = 'assets/images/npcs/monk/idle_left.png';
  static const String gomiland$assets_images_npcs_monk_idle_left_png = 'packages/gomiland/assets/images/npcs/monk/idle_left.png';

  static const String assets_images_npcs_monk_idle_right_png = 'assets/images/npcs/monk/idle_right.png';
  static const String gomiland$assets_images_npcs_monk_idle_right_png = 'packages/gomiland/assets/images/npcs/monk/idle_right.png';

  static const String assets_images_npcs_monk_idle_up_png = 'assets/images/npcs/monk/idle_up.png';
  static const String gomiland$assets_images_npcs_monk_idle_up_png = 'packages/gomiland/assets/images/npcs/monk/idle_up.png';

  static const String assets_images_npcs_monk_move_down_png = 'assets/images/npcs/monk/move_down.png';
  static const String gomiland$assets_images_npcs_monk_move_down_png = 'packages/gomiland/assets/images/npcs/monk/move_down.png';

  static const String assets_images_npcs_monk_move_left_png = 'assets/images/npcs/monk/move_left.png';
  static const String gomiland$assets_images_npcs_monk_move_left_png = 'packages/gomiland/assets/images/npcs/monk/move_left.png';

  static const String assets_images_npcs_monk_move_right_png = 'assets/images/npcs/monk/move_right.png';
  static const String gomiland$assets_images_npcs_monk_move_right_png = 'packages/gomiland/assets/images/npcs/monk/move_right.png';

  static const String assets_images_npcs_monk_move_up_png = 'assets/images/npcs/monk/move_up.png';
  static const String gomiland$assets_images_npcs_monk_move_up_png = 'packages/gomiland/assets/images/npcs/monk/move_up.png';

  static const String assets_images_player_idle_down_png = 'assets/images/player/idle_down.png';
  static const String gomiland$assets_images_player_idle_down_png = 'packages/gomiland/assets/images/player/idle_down.png';

  static const String assets_images_player_idle_left_png = 'assets/images/player/idle_left.png';
  static const String gomiland$assets_images_player_idle_left_png = 'packages/gomiland/assets/images/player/idle_left.png';

  static const String assets_images_player_idle_right_png = 'assets/images/player/idle_right.png';
  static const String gomiland$assets_images_player_idle_right_png = 'packages/gomiland/assets/images/player/idle_right.png';

  static const String assets_images_player_idle_up_png = 'assets/images/player/idle_up.png';
  static const String gomiland$assets_images_player_idle_up_png = 'packages/gomiland/assets/images/player/idle_up.png';

  static const String assets_images_player_move_down_png = 'assets/images/player/move_down.png';
  static const String gomiland$assets_images_player_move_down_png = 'packages/gomiland/assets/images/player/move_down.png';

  static const String assets_images_player_move_left_png = 'assets/images/player/move_left.png';
  static const String gomiland$assets_images_player_move_left_png = 'packages/gomiland/assets/images/player/move_left.png';

  static const String assets_images_player_move_right_png = 'assets/images/player/move_right.png';
  static const String gomiland$assets_images_player_move_right_png = 'packages/gomiland/assets/images/player/move_right.png';

  static const String assets_images_player_move_up_png = 'assets/images/player/move_up.png';
  static const String gomiland$assets_images_player_move_up_png = 'packages/gomiland/assets/images/player/move_up.png';

  static const String assets_images_spritesheets_coin_small_png = 'assets/images/spritesheets/coin_small.png';
  static const String gomiland$assets_images_spritesheets_coin_small_png = 'packages/gomiland/assets/images/spritesheets/coin_small.png';

  static const String assets_images_tiles_grass_json = 'assets/images/tiles/grass.json';
  static const String gomiland$assets_images_tiles_grass_json = 'packages/gomiland/assets/images/tiles/grass.json';

  static const String assets_images_tiles_grass_png = 'assets/images/tiles/grass.png';
  static const String gomiland$assets_images_tiles_grass_png = 'packages/gomiland/assets/images/tiles/grass.png';

  static const String assets_images_tiles_hood_base_json = 'assets/images/tiles/hood_base.json';
  static const String gomiland$assets_images_tiles_hood_base_json = 'packages/gomiland/assets/images/tiles/hood_base.json';

  static const String assets_images_tiles_pavement_json = 'assets/images/tiles/pavement.json';
  static const String gomiland$assets_images_tiles_pavement_json = 'packages/gomiland/assets/images/tiles/pavement.json';

  static const String assets_images_tiles_pavement_png = 'assets/images/tiles/pavement.png';
  static const String gomiland$assets_images_tiles_pavement_png = 'packages/gomiland/assets/images/tiles/pavement.png';

  static const String assets_images_tiles_sand_json = 'assets/images/tiles/sand.json';
  static const String gomiland$assets_images_tiles_sand_json = 'packages/gomiland/assets/images/tiles/sand.json';

  static const String assets_images_tiles_sand_png = 'assets/images/tiles/sand.png';
  static const String gomiland$assets_images_tiles_sand_png = 'packages/gomiland/assets/images/tiles/sand.png';

  static const String assets_images_tiles_water_json = 'assets/images/tiles/water.json';
  static const String gomiland$assets_images_tiles_water_json = 'packages/gomiland/assets/images/tiles/water.json';

  static const String assets_images_tiles_water_png = 'assets/images/tiles/water.png';
  static const String gomiland$assets_images_tiles_water_png = 'packages/gomiland/assets/images/tiles/water.png';

  static const String assets_images_tiles_waterfront_json = 'assets/images/tiles/waterfront.json';
  static const String gomiland$assets_images_tiles_waterfront_json = 'packages/gomiland/assets/images/tiles/waterfront.json';

  static const String assets_images_tiles_waterfront_png = 'assets/images/tiles/waterfront.png';
  static const String gomiland$assets_images_tiles_waterfront_png = 'packages/gomiland/assets/images/tiles/waterfront.png';
}
