// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 243.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'gomiland';

  static const String assets_audio_bgm_behind_the_rocks_mp3 = 'assets/audio/bgm/behind_the_rocks.mp3';
  static const String gomiland$assets_audio_bgm_behind_the_rocks_mp3 = 'packages/gomiland/assets/audio/bgm/behind_the_rocks.mp3';

  static const String assets_audio_bgm_hood_bgm_mp3 = 'assets/audio/bgm/hood_bgm.mp3';
  static const String gomiland$assets_audio_bgm_hood_bgm_mp3 = 'packages/gomiland/assets/audio/bgm/hood_bgm.mp3';

  static const String assets_audio_bgm_olib_oil_mp3 = 'assets/audio/bgm/olib_oil.mp3';
  static const String gomiland$assets_audio_bgm_olib_oil_mp3 = 'packages/gomiland/assets/audio/bgm/olib_oil.mp3';

  static const String assets_audio_bgm_park_bgm_mp3 = 'assets/audio/bgm/park_bgm.mp3';
  static const String gomiland$assets_audio_bgm_park_bgm_mp3 = 'packages/gomiland/assets/audio/bgm/park_bgm.mp3';

  static const String assets_audio_sfx_correct_mp3 = 'assets/audio/sfx/correct.mp3';
  static const String gomiland$assets_audio_sfx_correct_mp3 = 'packages/gomiland/assets/audio/sfx/correct.mp3';

  static const String assets_audio_sfx_incorrect_mp3 = 'assets/audio/sfx/incorrect.mp3';
  static const String gomiland$assets_audio_sfx_incorrect_mp3 = 'packages/gomiland/assets/audio/sfx/incorrect.mp3';

  static const String assets_audio_sfx_next_mp3 = 'assets/audio/sfx/next.mp3';
  static const String gomiland$assets_audio_sfx_next_mp3 = 'packages/gomiland/assets/audio/sfx/next.mp3';

  static const String assets_audio_sfx_pickup_mp3 = 'assets/audio/sfx/pickup.mp3';
  static const String gomiland$assets_audio_sfx_pickup_mp3 = 'packages/gomiland/assets/audio/sfx/pickup.mp3';

  static const String assets_images_buildings_apt1_png = 'assets/images/buildings/apt1.png';
  static const String gomiland$assets_images_buildings_apt1_png = 'packages/gomiland/assets/images/buildings/apt1.png';

  static const String assets_images_buildings_apt2_png = 'assets/images/buildings/apt2.png';
  static const String gomiland$assets_images_buildings_apt2_png = 'packages/gomiland/assets/images/buildings/apt2.png';

  static const String assets_images_buildings_apt3_png = 'assets/images/buildings/apt3.png';
  static const String gomiland$assets_images_buildings_apt3_png = 'packages/gomiland/assets/images/buildings/apt3.png';

  static const String assets_images_buildings_apt_side_png = 'assets/images/buildings/apt_side.png';
  static const String gomiland$assets_images_buildings_apt_side_png = 'packages/gomiland/assets/images/buildings/apt_side.png';

  static const String assets_images_buildings_beehive_png = 'assets/images/buildings/beehive.png';
  static const String gomiland$assets_images_buildings_beehive_png = 'packages/gomiland/assets/images/buildings/beehive.png';

  static const String assets_images_buildings_cafe_png = 'assets/images/buildings/cafe.png';
  static const String gomiland$assets_images_buildings_cafe_png = 'packages/gomiland/assets/images/buildings/cafe.png';

  static const String assets_images_buildings_castle_png = 'assets/images/buildings/castle.png';
  static const String gomiland$assets_images_buildings_castle_png = 'packages/gomiland/assets/images/buildings/castle.png';

  static const String assets_images_buildings_charms_png = 'assets/images/buildings/charms.png';
  static const String gomiland$assets_images_buildings_charms_png = 'packages/gomiland/assets/images/buildings/charms.png';

  static const String assets_images_buildings_charms_bare_png = 'assets/images/buildings/charms_bare.png';
  static const String gomiland$assets_images_buildings_charms_bare_png = 'packages/gomiland/assets/images/buildings/charms_bare.png';

  static const String assets_images_buildings_combini_png = 'assets/images/buildings/combini.png';
  static const String gomiland$assets_images_buildings_combini_png = 'packages/gomiland/assets/images/buildings/combini.png';

  static const String assets_images_buildings_fish_shop_png = 'assets/images/buildings/fish_shop.png';
  static const String gomiland$assets_images_buildings_fish_shop_png = 'packages/gomiland/assets/images/buildings/fish_shop.png';

  static const String assets_images_buildings_home_png = 'assets/images/buildings/home.png';
  static const String gomiland$assets_images_buildings_home_png = 'packages/gomiland/assets/images/buildings/home.png';

  static const String assets_images_buildings_hospital_png = 'assets/images/buildings/hospital.png';
  static const String gomiland$assets_images_buildings_hospital_png = 'packages/gomiland/assets/images/buildings/hospital.png';

  static const String assets_images_buildings_houses_eng_png = 'assets/images/buildings/houses_eng.png';
  static const String gomiland$assets_images_buildings_houses_eng_png = 'packages/gomiland/assets/images/buildings/houses_eng.png';

  static const String assets_images_buildings_inn_png = 'assets/images/buildings/inn.png';
  static const String gomiland$assets_images_buildings_inn_png = 'packages/gomiland/assets/images/buildings/inn.png';

  static const String assets_images_buildings_kiosk_roof_png = 'assets/images/buildings/kiosk_roof.png';
  static const String gomiland$assets_images_buildings_kiosk_roof_png = 'packages/gomiland/assets/images/buildings/kiosk_roof.png';

  static const String assets_images_buildings_office_png = 'assets/images/buildings/office.png';
  static const String gomiland$assets_images_buildings_office_png = 'packages/gomiland/assets/images/buildings/office.png';

  static const String assets_images_buildings_park_centre1_png = 'assets/images/buildings/park_centre1.png';
  static const String gomiland$assets_images_buildings_park_centre1_png = 'packages/gomiland/assets/images/buildings/park_centre1.png';

  static const String assets_images_buildings_park_centre2_png = 'assets/images/buildings/park_centre2.png';
  static const String gomiland$assets_images_buildings_park_centre2_png = 'packages/gomiland/assets/images/buildings/park_centre2.png';

  static const String assets_images_buildings_pilar_png = 'assets/images/buildings/pilar.png';
  static const String gomiland$assets_images_buildings_pilar_png = 'packages/gomiland/assets/images/buildings/pilar.png';

  static const String assets_images_buildings_school_png = 'assets/images/buildings/school.png';
  static const String gomiland$assets_images_buildings_school_png = 'packages/gomiland/assets/images/buildings/school.png';

  static const String assets_images_buildings_shop_back_eng_png = 'assets/images/buildings/shop_back_eng.png';
  static const String gomiland$assets_images_buildings_shop_back_eng_png = 'packages/gomiland/assets/images/buildings/shop_back_eng.png';

  static const String assets_images_buildings_shop_back_jap_png = 'assets/images/buildings/shop_back_jap.png';
  static const String gomiland$assets_images_buildings_shop_back_jap_png = 'packages/gomiland/assets/images/buildings/shop_back_jap.png';

  static const String assets_images_buildings_shop_back_jap1_png = 'assets/images/buildings/shop_back_jap1.png';
  static const String gomiland$assets_images_buildings_shop_back_jap1_png = 'packages/gomiland/assets/images/buildings/shop_back_jap1.png';

  static const String assets_images_buildings_shop_side_eng_png = 'assets/images/buildings/shop_side_eng.png';
  static const String gomiland$assets_images_buildings_shop_side_eng_png = 'packages/gomiland/assets/images/buildings/shop_side_eng.png';

  static const String assets_images_buildings_shop_side_jap_png = 'assets/images/buildings/shop_side_jap.png';
  static const String gomiland$assets_images_buildings_shop_side_jap_png = 'packages/gomiland/assets/images/buildings/shop_side_jap.png';

  static const String assets_images_buildings_shops_eng_png = 'assets/images/buildings/shops_eng.png';
  static const String gomiland$assets_images_buildings_shops_eng_png = 'packages/gomiland/assets/images/buildings/shops_eng.png';

  static const String assets_images_buildings_shoukudou_png = 'assets/images/buildings/shoukudou.png';
  static const String gomiland$assets_images_buildings_shoukudou_png = 'packages/gomiland/assets/images/buildings/shoukudou.png';

  static const String assets_images_buildings_shrine1_png = 'assets/images/buildings/shrine1.png';
  static const String gomiland$assets_images_buildings_shrine1_png = 'packages/gomiland/assets/images/buildings/shrine1.png';

  static const String assets_images_buildings_shrine2_png = 'assets/images/buildings/shrine2.png';
  static const String gomiland$assets_images_buildings_shrine2_png = 'packages/gomiland/assets/images/buildings/shrine2.png';

  static const String assets_images_buildings_shrine3_png = 'assets/images/buildings/shrine3.png';
  static const String gomiland$assets_images_buildings_shrine3_png = 'packages/gomiland/assets/images/buildings/shrine3.png';

  static const String assets_images_buildings_shrine_office_png = 'assets/images/buildings/shrine_office.png';
  static const String gomiland$assets_images_buildings_shrine_office_png = 'packages/gomiland/assets/images/buildings/shrine_office.png';

  static const String assets_images_buildings_soup_kitchen_png = 'assets/images/buildings/soup_kitchen.png';
  static const String gomiland$assets_images_buildings_soup_kitchen_png = 'packages/gomiland/assets/images/buildings/soup_kitchen.png';

  static const String assets_images_buildings_tea_shop_png = 'assets/images/buildings/tea_shop.png';
  static const String gomiland$assets_images_buildings_tea_shop_png = 'packages/gomiland/assets/images/buildings/tea_shop.png';

  static const String assets_images_buildings_temple_png = 'assets/images/buildings/temple.png';
  static const String gomiland$assets_images_buildings_temple_png = 'packages/gomiland/assets/images/buildings/temple.png';

  static const String assets_images_buildings_tori_big_png = 'assets/images/buildings/tori_big.png';
  static const String gomiland$assets_images_buildings_tori_big_png = 'packages/gomiland/assets/images/buildings/tori_big.png';

  static const String assets_images_buildings_tori_small_png = 'assets/images/buildings/tori_small.png';
  static const String gomiland$assets_images_buildings_tori_small_png = 'packages/gomiland/assets/images/buildings/tori_small.png';

  static const String assets_images_buildings_waterhouse_png = 'assets/images/buildings/waterhouse.png';
  static const String gomiland$assets_images_buildings_waterhouse_png = 'packages/gomiland/assets/images/buildings/waterhouse.png';

  static const String assets_images_logo_gomiland_icon_png = 'assets/images/logo/gomiland_icon.png';
  static const String gomiland$assets_images_logo_gomiland_icon_png = 'packages/gomiland/assets/images/logo/gomiland_icon.png';

  static const String assets_images_logo_gomiland_simple_png = 'assets/images/logo/gomiland_simple.png';
  static const String gomiland$assets_images_logo_gomiland_simple_png = 'packages/gomiland/assets/images/logo/gomiland_simple.png';

  static const String assets_images_npcs_anri_png = 'assets/images/npcs/anri.png';
  static const String gomiland$assets_images_npcs_anri_png = 'packages/gomiland/assets/images/npcs/anri.png';

  static const String assets_images_npcs_asimov_png = 'assets/images/npcs/asimov.png';
  static const String gomiland$assets_images_npcs_asimov_png = 'packages/gomiland/assets/images/npcs/asimov.png';

  static const String assets_images_npcs_boss_png = 'assets/images/npcs/boss.png';
  static const String gomiland$assets_images_npcs_boss_png = 'packages/gomiland/assets/images/npcs/boss.png';

  static const String assets_images_npcs_boy_png = 'assets/images/npcs/boy.png';
  static const String gomiland$assets_images_npcs_boy_png = 'packages/gomiland/assets/images/npcs/boy.png';

  static const String assets_images_npcs_florence_png = 'assets/images/npcs/florence.png';
  static const String gomiland$assets_images_npcs_florence_png = 'packages/gomiland/assets/images/npcs/florence.png';

  static const String assets_images_npcs_gaia_png = 'assets/images/npcs/gaia.png';
  static const String gomiland$assets_images_npcs_gaia_png = 'packages/gomiland/assets/images/npcs/gaia.png';

  static const String assets_images_npcs_girl_png = 'assets/images/npcs/girl.png';
  static const String gomiland$assets_images_npcs_girl_png = 'packages/gomiland/assets/images/npcs/girl.png';

  static const String assets_images_npcs_himiko_png = 'assets/images/npcs/himiko.png';
  static const String gomiland$assets_images_npcs_himiko_png = 'packages/gomiland/assets/images/npcs/himiko.png';

  static const String assets_images_npcs_man_png = 'assets/images/npcs/man.png';
  static const String gomiland$assets_images_npcs_man_png = 'packages/gomiland/assets/images/npcs/man.png';

  static const String assets_images_npcs_manuka_png = 'assets/images/npcs/manuka.png';
  static const String gomiland$assets_images_npcs_manuka_png = 'packages/gomiland/assets/images/npcs/manuka.png';

  static const String assets_images_npcs_moon_png = 'assets/images/npcs/moon.png';
  static const String gomiland$assets_images_npcs_moon_png = 'packages/gomiland/assets/images/npcs/moon.png';

  static const String assets_images_npcs_mr_star_png = 'assets/images/npcs/mr_star.png';
  static const String gomiland$assets_images_npcs_mr_star_png = 'packages/gomiland/assets/images/npcs/mr_star.png';

  static const String assets_images_npcs_mrs_star_png = 'assets/images/npcs/mrs_star.png';
  static const String gomiland$assets_images_npcs_mrs_star_png = 'packages/gomiland/assets/images/npcs/mrs_star.png';

  static const String assets_images_npcs_ms_margret_png = 'assets/images/npcs/ms_margret.png';
  static const String gomiland$assets_images_npcs_ms_margret_png = 'packages/gomiland/assets/images/npcs/ms_margret.png';

  static const String assets_images_npcs_muscle_man_png = 'assets/images/npcs/muscle_man.png';
  static const String gomiland$assets_images_npcs_muscle_man_png = 'packages/gomiland/assets/images/npcs/muscle_man.png';

  static const String assets_images_npcs_qianbi_png = 'assets/images/npcs/qianbi.png';
  static const String gomiland$assets_images_npcs_qianbi_png = 'packages/gomiland/assets/images/npcs/qianbi.png';

  static const String assets_images_npcs_ranger_png = 'assets/images/npcs/ranger.png';
  static const String gomiland$assets_images_npcs_ranger_png = 'packages/gomiland/assets/images/npcs/ranger.png';

  static const String assets_images_npcs_risa_png = 'assets/images/npcs/risa.png';
  static const String gomiland$assets_images_npcs_risa_png = 'packages/gomiland/assets/images/npcs/risa.png';

  static const String assets_images_npcs_scarlett_png = 'assets/images/npcs/scarlett.png';
  static const String gomiland$assets_images_npcs_scarlett_png = 'packages/gomiland/assets/images/npcs/scarlett.png';

  static const String assets_images_npcs_stark_png = 'assets/images/npcs/stark.png';
  static const String gomiland$assets_images_npcs_stark_png = 'packages/gomiland/assets/images/npcs/stark.png';

  static const String assets_images_npcs_woman_png = 'assets/images/npcs/woman.png';
  static const String gomiland$assets_images_npcs_woman_png = 'packages/gomiland/assets/images/npcs/woman.png';

  static const String assets_images_objects_digger_png = 'assets/images/objects/digger.png';
  static const String gomiland$assets_images_objects_digger_png = 'packages/gomiland/assets/images/objects/digger.png';

  static const String assets_images_objects_general_sign_png = 'assets/images/objects/general_sign.png';
  static const String gomiland$assets_images_objects_general_sign_png = 'packages/gomiland/assets/images/objects/general_sign.png';

  static const String assets_images_objects_go_sign_png = 'assets/images/objects/go_sign.png';
  static const String gomiland$assets_images_objects_go_sign_png = 'packages/gomiland/assets/images/objects/go_sign.png';

  static const String assets_images_objects_light_png = 'assets/images/objects/light.png';
  static const String gomiland$assets_images_objects_light_png = 'packages/gomiland/assets/images/objects/light.png';

  static const String assets_images_objects_park_lamp_png = 'assets/images/objects/park_lamp.png';
  static const String gomiland$assets_images_objects_park_lamp_png = 'packages/gomiland/assets/images/objects/park_lamp.png';

  static const String assets_images_objects_piler_png = 'assets/images/objects/piler.png';
  static const String gomiland$assets_images_objects_piler_png = 'packages/gomiland/assets/images/objects/piler.png';

  static const String assets_images_objects_rock_small_png = 'assets/images/objects/rock_small.png';
  static const String gomiland$assets_images_objects_rock_small_png = 'packages/gomiland/assets/images/objects/rock_small.png';

  static const String assets_images_objects_rock_tall_png = 'assets/images/objects/rock_tall.png';
  static const String gomiland$assets_images_objects_rock_tall_png = 'packages/gomiland/assets/images/objects/rock_tall.png';

  static const String assets_images_objects_samurai_png = 'assets/images/objects/samurai.png';
  static const String gomiland$assets_images_objects_samurai_png = 'packages/gomiland/assets/images/objects/samurai.png';

  static const String assets_images_objects_stone_light_png = 'assets/images/objects/stone_light.png';
  static const String gomiland$assets_images_objects_stone_light_png = 'packages/gomiland/assets/images/objects/stone_light.png';

  static const String assets_images_objects_street_lamp_png = 'assets/images/objects/street_lamp.png';
  static const String gomiland$assets_images_objects_street_lamp_png = 'packages/gomiland/assets/images/objects/street_lamp.png';

  static const String assets_images_objects_vacbot_png = 'assets/images/objects/vacbot.png';
  static const String gomiland$assets_images_objects_vacbot_png = 'packages/gomiland/assets/images/objects/vacbot.png';

  static const String assets_images_player_female_png = 'assets/images/player/female.png';
  static const String gomiland$assets_images_player_female_png = 'packages/gomiland/assets/images/player/female.png';

  static const String assets_images_player_male_png = 'assets/images/player/male.png';
  static const String gomiland$assets_images_player_male_png = 'packages/gomiland/assets/images/player/male.png';

  static const String assets_images_rubbish_apple_png = 'assets/images/rubbish/apple.png';
  static const String gomiland$assets_images_rubbish_apple_png = 'packages/gomiland/assets/images/rubbish/apple.png';

  static const String assets_images_rubbish_banana_png = 'assets/images/rubbish/banana.png';
  static const String gomiland$assets_images_rubbish_banana_png = 'packages/gomiland/assets/images/rubbish/banana.png';

  static const String assets_images_rubbish_battery_png = 'assets/images/rubbish/battery.png';
  static const String gomiland$assets_images_rubbish_battery_png = 'packages/gomiland/assets/images/rubbish/battery.png';

  static const String assets_images_rubbish_bowl_png = 'assets/images/rubbish/bowl.png';
  static const String gomiland$assets_images_rubbish_bowl_png = 'packages/gomiland/assets/images/rubbish/bowl.png';

  static const String assets_images_rubbish_burrito_png = 'assets/images/rubbish/burrito.png';
  static const String gomiland$assets_images_rubbish_burrito_png = 'packages/gomiland/assets/images/rubbish/burrito.png';

  static const String assets_images_rubbish_calendar_png = 'assets/images/rubbish/calendar.png';
  static const String gomiland$assets_images_rubbish_calendar_png = 'packages/gomiland/assets/images/rubbish/calendar.png';

  static const String assets_images_rubbish_chicken_leg_png = 'assets/images/rubbish/chicken_leg.png';
  static const String gomiland$assets_images_rubbish_chicken_leg_png = 'packages/gomiland/assets/images/rubbish/chicken_leg.png';

  static const String assets_images_rubbish_container_png = 'assets/images/rubbish/container.png';
  static const String gomiland$assets_images_rubbish_container_png = 'packages/gomiland/assets/images/rubbish/container.png';

  static const String assets_images_rubbish_cup_noodles_png = 'assets/images/rubbish/cup_noodles.png';
  static const String gomiland$assets_images_rubbish_cup_noodles_png = 'packages/gomiland/assets/images/rubbish/cup_noodles.png';

  static const String assets_images_rubbish_detegent_bottle_png = 'assets/images/rubbish/detegent_bottle.png';
  static const String gomiland$assets_images_rubbish_detegent_bottle_png = 'packages/gomiland/assets/images/rubbish/detegent_bottle.png';

  static const String assets_images_rubbish_e_drone_png = 'assets/images/rubbish/e_drone.png';
  static const String gomiland$assets_images_rubbish_e_drone_png = 'packages/gomiland/assets/images/rubbish/e_drone.png';

  static const String assets_images_rubbish_egg_png = 'assets/images/rubbish/egg.png';
  static const String gomiland$assets_images_rubbish_egg_png = 'packages/gomiland/assets/images/rubbish/egg.png';

  static const String assets_images_rubbish_egg_tray_png = 'assets/images/rubbish/egg_tray.png';
  static const String gomiland$assets_images_rubbish_egg_tray_png = 'packages/gomiland/assets/images/rubbish/egg_tray.png';

  static const String assets_images_rubbish_fork_png = 'assets/images/rubbish/fork.png';
  static const String gomiland$assets_images_rubbish_fork_png = 'packages/gomiland/assets/images/rubbish/fork.png';

  static const String assets_images_rubbish_gameboy_png = 'assets/images/rubbish/gameboy.png';
  static const String gomiland$assets_images_rubbish_gameboy_png = 'packages/gomiland/assets/images/rubbish/gameboy.png';

  static const String assets_images_rubbish_glass_bottle_png = 'assets/images/rubbish/glass_bottle.png';
  static const String gomiland$assets_images_rubbish_glass_bottle_png = 'packages/gomiland/assets/images/rubbish/glass_bottle.png';

  static const String assets_images_rubbish_glass_jar_png = 'assets/images/rubbish/glass_jar.png';
  static const String gomiland$assets_images_rubbish_glass_jar_png = 'packages/gomiland/assets/images/rubbish/glass_jar.png';

  static const String assets_images_rubbish_glass_mug_png = 'assets/images/rubbish/glass_mug.png';
  static const String gomiland$assets_images_rubbish_glass_mug_png = 'packages/gomiland/assets/images/rubbish/glass_mug.png';

  static const String assets_images_rubbish_laptop_png = 'assets/images/rubbish/laptop.png';
  static const String gomiland$assets_images_rubbish_laptop_png = 'packages/gomiland/assets/images/rubbish/laptop.png';

  static const String assets_images_rubbish_letter_png = 'assets/images/rubbish/letter.png';
  static const String gomiland$assets_images_rubbish_letter_png = 'packages/gomiland/assets/images/rubbish/letter.png';

  static const String assets_images_rubbish_metal_cans_png = 'assets/images/rubbish/metal_cans.png';
  static const String gomiland$assets_images_rubbish_metal_cans_png = 'packages/gomiland/assets/images/rubbish/metal_cans.png';

  static const String assets_images_rubbish_metal_tins_png = 'assets/images/rubbish/metal_tins.png';
  static const String gomiland$assets_images_rubbish_metal_tins_png = 'packages/gomiland/assets/images/rubbish/metal_tins.png';

  static const String assets_images_rubbish_milk_carton_png = 'assets/images/rubbish/milk_carton.png';
  static const String gomiland$assets_images_rubbish_milk_carton_png = 'packages/gomiland/assets/images/rubbish/milk_carton.png';

  static const String assets_images_rubbish_mobile_png = 'assets/images/rubbish/mobile.png';
  static const String gomiland$assets_images_rubbish_mobile_png = 'packages/gomiland/assets/images/rubbish/mobile.png';

  static const String assets_images_rubbish_newspaper_png = 'assets/images/rubbish/newspaper.png';
  static const String gomiland$assets_images_rubbish_newspaper_png = 'packages/gomiland/assets/images/rubbish/newspaper.png';

  static const String assets_images_rubbish_pan_png = 'assets/images/rubbish/pan.png';
  static const String gomiland$assets_images_rubbish_pan_png = 'packages/gomiland/assets/images/rubbish/pan.png';

  static const String assets_images_rubbish_paper_bag_png = 'assets/images/rubbish/paper_bag.png';
  static const String gomiland$assets_images_rubbish_paper_bag_png = 'packages/gomiland/assets/images/rubbish/paper_bag.png';

  static const String assets_images_rubbish_paper_cardboard_png = 'assets/images/rubbish/paper_cardboard.png';
  static const String gomiland$assets_images_rubbish_paper_cardboard_png = 'packages/gomiland/assets/images/rubbish/paper_cardboard.png';

  static const String assets_images_rubbish_paper_fliers_png = 'assets/images/rubbish/paper_fliers.png';
  static const String gomiland$assets_images_rubbish_paper_fliers_png = 'packages/gomiland/assets/images/rubbish/paper_fliers.png';

  static const String assets_images_rubbish_pizza_png = 'assets/images/rubbish/pizza.png';
  static const String gomiland$assets_images_rubbish_pizza_png = 'packages/gomiland/assets/images/rubbish/pizza.png';

  static const String assets_images_rubbish_plastic_bag_png = 'assets/images/rubbish/plastic_bag.png';
  static const String gomiland$assets_images_rubbish_plastic_bag_png = 'packages/gomiland/assets/images/rubbish/plastic_bag.png';

  static const String assets_images_rubbish_plastic_bottle_png = 'assets/images/rubbish/plastic_bottle.png';
  static const String gomiland$assets_images_rubbish_plastic_bottle_png = 'packages/gomiland/assets/images/rubbish/plastic_bottle.png';

  static const String assets_images_rubbish_plastic_cup_png = 'assets/images/rubbish/plastic_cup.png';
  static const String gomiland$assets_images_rubbish_plastic_cup_png = 'packages/gomiland/assets/images/rubbish/plastic_cup.png';

  static const String assets_images_rubbish_plate_png = 'assets/images/rubbish/plate.png';
  static const String gomiland$assets_images_rubbish_plate_png = 'packages/gomiland/assets/images/rubbish/plate.png';

  static const String assets_images_rubbish_pot_png = 'assets/images/rubbish/pot.png';
  static const String gomiland$assets_images_rubbish_pot_png = 'packages/gomiland/assets/images/rubbish/pot.png';

  static const String assets_images_rubbish_rubbish_small_png = 'assets/images/rubbish/rubbish_small.png';
  static const String gomiland$assets_images_rubbish_rubbish_small_png = 'packages/gomiland/assets/images/rubbish/rubbish_small.png';

  static const String assets_images_rubbish_sandwich_png = 'assets/images/rubbish/sandwich.png';
  static const String gomiland$assets_images_rubbish_sandwich_png = 'packages/gomiland/assets/images/rubbish/sandwich.png';

  static const String assets_images_rubbish_spanner_png = 'assets/images/rubbish/spanner.png';
  static const String gomiland$assets_images_rubbish_spanner_png = 'packages/gomiland/assets/images/rubbish/spanner.png';

  static const String assets_images_rubbish_spoon_png = 'assets/images/rubbish/spoon.png';
  static const String gomiland$assets_images_rubbish_spoon_png = 'packages/gomiland/assets/images/rubbish/spoon.png';

  static const String assets_images_rubbish_straw_png = 'assets/images/rubbish/straw.png';
  static const String gomiland$assets_images_rubbish_straw_png = 'packages/gomiland/assets/images/rubbish/straw.png';

  static const String assets_images_rubbish_tablet_png = 'assets/images/rubbish/tablet.png';
  static const String gomiland$assets_images_rubbish_tablet_png = 'packages/gomiland/assets/images/rubbish/tablet.png';

  static const String assets_images_rubbish_teapot_png = 'assets/images/rubbish/teapot.png';
  static const String gomiland$assets_images_rubbish_teapot_png = 'packages/gomiland/assets/images/rubbish/teapot.png';

  static const String assets_images_rubbish_toilet_roll_png = 'assets/images/rubbish/toilet_roll.png';
  static const String gomiland$assets_images_rubbish_toilet_roll_png = 'packages/gomiland/assets/images/rubbish/toilet_roll.png';

  static const String assets_images_rubbish_wine_glass_png = 'assets/images/rubbish/wine_glass.png';
  static const String gomiland$assets_images_rubbish_wine_glass_png = 'packages/gomiland/assets/images/rubbish/wine_glass.png';

  static const String assets_images_spritesheets_beehive_png = 'assets/images/spritesheets/beehive.png';
  static const String gomiland$assets_images_spritesheets_beehive_png = 'packages/gomiland/assets/images/spritesheets/beehive.png';

  static const String assets_images_spritesheets_coin_small_png = 'assets/images/spritesheets/coin_small.png';
  static const String gomiland$assets_images_spritesheets_coin_small_png = 'packages/gomiland/assets/images/spritesheets/coin_small.png';

  static const String assets_images_spritesheets_fountain_png = 'assets/images/spritesheets/fountain.png';
  static const String gomiland$assets_images_spritesheets_fountain_png = 'packages/gomiland/assets/images/spritesheets/fountain.png';

  static const String assets_images_spritesheets_piler_png = 'assets/images/spritesheets/piler.png';
  static const String gomiland$assets_images_spritesheets_piler_png = 'packages/gomiland/assets/images/spritesheets/piler.png';

  static const String assets_images_spritesheets_temizuya_png = 'assets/images/spritesheets/temizuya.png';
  static const String gomiland$assets_images_spritesheets_temizuya_png = 'packages/gomiland/assets/images/spritesheets/temizuya.png';

  static const String assets_images_tile_maps_bamboo_png = 'assets/images/tile_maps/bamboo.png';
  static const String gomiland$assets_images_tile_maps_bamboo_png = 'packages/gomiland/assets/images/tile_maps/bamboo.png';

  static const String assets_images_tile_maps_bins_png = 'assets/images/tile_maps/bins.png';
  static const String gomiland$assets_images_tile_maps_bins_png = 'packages/gomiland/assets/images/tile_maps/bins.png';

  static const String assets_images_tile_maps_bonsai_png = 'assets/images/tile_maps/bonsai.png';
  static const String gomiland$assets_images_tile_maps_bonsai_png = 'packages/gomiland/assets/images/tile_maps/bonsai.png';

  static const String assets_images_tile_maps_bridge_rail_png = 'assets/images/tile_maps/bridge_rail.png';
  static const String gomiland$assets_images_tile_maps_bridge_rail_png = 'packages/gomiland/assets/images/tile_maps/bridge_rail.png';

  static const String assets_images_tile_maps_buildings_png = 'assets/images/tile_maps/buildings.png';
  static const String gomiland$assets_images_tile_maps_buildings_png = 'packages/gomiland/assets/images/tile_maps/buildings.png';

  static const String assets_images_tile_maps_fence_png = 'assets/images/tile_maps/fence.png';
  static const String gomiland$assets_images_tile_maps_fence_png = 'packages/gomiland/assets/images/tile_maps/fence.png';

  static const String assets_images_tile_maps_grass_png = 'assets/images/tile_maps/grass.png';
  static const String gomiland$assets_images_tile_maps_grass_png = 'packages/gomiland/assets/images/tile_maps/grass.png';

  static const String assets_images_tile_maps_grass_barriers_png = 'assets/images/tile_maps/grass_barriers.png';
  static const String gomiland$assets_images_tile_maps_grass_barriers_png = 'packages/gomiland/assets/images/tile_maps/grass_barriers.png';

  static const String assets_images_tile_maps_houses_japanese_png = 'assets/images/tile_maps/houses_japanese.png';
  static const String gomiland$assets_images_tile_maps_houses_japanese_png = 'packages/gomiland/assets/images/tile_maps/houses_japanese.png';

  static const String assets_images_tile_maps_mini_hood_png = 'assets/images/tile_maps/mini_hood.png';
  static const String gomiland$assets_images_tile_maps_mini_hood_png = 'packages/gomiland/assets/images/tile_maps/mini_hood.png';

  static const String assets_images_tile_maps_mini_park_png = 'assets/images/tile_maps/mini_park.png';
  static const String gomiland$assets_images_tile_maps_mini_park_png = 'packages/gomiland/assets/images/tile_maps/mini_park.png';

  static const String assets_images_tile_maps_objects_grass_png = 'assets/images/tile_maps/objects_grass.png';
  static const String gomiland$assets_images_tile_maps_objects_grass_png = 'packages/gomiland/assets/images/tile_maps/objects_grass.png';

  static const String assets_images_tile_maps_objects_street_png = 'assets/images/tile_maps/objects_street.png';
  static const String gomiland$assets_images_tile_maps_objects_street_png = 'packages/gomiland/assets/images/tile_maps/objects_street.png';

  static const String assets_images_tile_maps_park_overlay_png = 'assets/images/tile_maps/park_overlay.png';
  static const String gomiland$assets_images_tile_maps_park_overlay_png = 'packages/gomiland/assets/images/tile_maps/park_overlay.png';

  static const String assets_images_tile_maps_pavement_png = 'assets/images/tile_maps/pavement.png';
  static const String gomiland$assets_images_tile_maps_pavement_png = 'packages/gomiland/assets/images/tile_maps/pavement.png';

  static const String assets_images_tile_maps_rock_wall_png = 'assets/images/tile_maps/rock_wall.png';
  static const String gomiland$assets_images_tile_maps_rock_wall_png = 'packages/gomiland/assets/images/tile_maps/rock_wall.png';

  static const String assets_images_tile_maps_room_png = 'assets/images/tile_maps/room.png';
  static const String gomiland$assets_images_tile_maps_room_png = 'packages/gomiland/assets/images/tile_maps/room.png';

  static const String assets_images_tile_maps_room_door_png = 'assets/images/tile_maps/room_door.png';
  static const String gomiland$assets_images_tile_maps_room_door_png = 'packages/gomiland/assets/images/tile_maps/room_door.png';

  static const String assets_images_tile_maps_sand_png = 'assets/images/tile_maps/sand.png';
  static const String gomiland$assets_images_tile_maps_sand_png = 'packages/gomiland/assets/images/tile_maps/sand.png';

  static const String assets_images_tile_maps_street_overlays_png = 'assets/images/tile_maps/street_overlays.png';
  static const String gomiland$assets_images_tile_maps_street_overlays_png = 'packages/gomiland/assets/images/tile_maps/street_overlays.png';

  static const String assets_images_tile_maps_table_png = 'assets/images/tile_maps/table.png';
  static const String gomiland$assets_images_tile_maps_table_png = 'packages/gomiland/assets/images/tile_maps/table.png';

  static const String assets_images_tile_maps_track_fence_png = 'assets/images/tile_maps/track_fence.png';
  static const String gomiland$assets_images_tile_maps_track_fence_png = 'packages/gomiland/assets/images/tile_maps/track_fence.png';

  static const String assets_images_tile_maps_transitions_png = 'assets/images/tile_maps/transitions.png';
  static const String gomiland$assets_images_tile_maps_transitions_png = 'packages/gomiland/assets/images/tile_maps/transitions.png';

  static const String assets_images_tile_maps_trees_png = 'assets/images/tile_maps/trees.png';
  static const String gomiland$assets_images_tile_maps_trees_png = 'packages/gomiland/assets/images/tile_maps/trees.png';

  static const String assets_images_tile_maps_wall_png = 'assets/images/tile_maps/wall.png';
  static const String gomiland$assets_images_tile_maps_wall_png = 'packages/gomiland/assets/images/tile_maps/wall.png';

  static const String assets_images_tile_maps_wall_thick_png = 'assets/images/tile_maps/wall_thick.png';
  static const String gomiland$assets_images_tile_maps_wall_thick_png = 'packages/gomiland/assets/images/tile_maps/wall_thick.png';

  static const String assets_images_tile_maps_water_png = 'assets/images/tile_maps/water.png';
  static const String gomiland$assets_images_tile_maps_water_png = 'packages/gomiland/assets/images/tile_maps/water.png';

  static const String assets_images_tile_maps_waterfront_png = 'assets/images/tile_maps/waterfront.png';
  static const String gomiland$assets_images_tile_maps_waterfront_png = 'packages/gomiland/assets/images/tile_maps/waterfront.png';

  static const String assets_images_tile_maps_wood_base_png = 'assets/images/tile_maps/wood_base.png';
  static const String gomiland$assets_images_tile_maps_wood_base_png = 'packages/gomiland/assets/images/tile_maps/wood_base.png';

  static const String assets_images_trees_tree_bonsai_png = 'assets/images/trees/tree_bonsai.png';
  static const String gomiland$assets_images_trees_tree_bonsai_png = 'packages/gomiland/assets/images/trees/tree_bonsai.png';

  static const String assets_images_trees_tree_cone_png = 'assets/images/trees/tree_cone.png';
  static const String gomiland$assets_images_trees_tree_cone_png = 'packages/gomiland/assets/images/trees/tree_cone.png';

  static const String assets_images_trees_tree_fluffy_png = 'assets/images/trees/tree_fluffy.png';
  static const String gomiland$assets_images_trees_tree_fluffy_png = 'packages/gomiland/assets/images/trees/tree_fluffy.png';

  static const String assets_images_trees_tree_normal_png = 'assets/images/trees/tree_normal.png';
  static const String gomiland$assets_images_trees_tree_normal_png = 'packages/gomiland/assets/images/trees/tree_normal.png';

  static const String assets_images_trees_tree_orange_png = 'assets/images/trees/tree_orange.png';
  static const String gomiland$assets_images_trees_tree_orange_png = 'packages/gomiland/assets/images/trees/tree_orange.png';

  static const String assets_images_trees_tree_popsicle_png = 'assets/images/trees/tree_popsicle.png';
  static const String gomiland$assets_images_trees_tree_popsicle_png = 'packages/gomiland/assets/images/trees/tree_popsicle.png';

  static const String assets_images_trees_tree_sakura_png = 'assets/images/trees/tree_sakura.png';
  static const String gomiland$assets_images_trees_tree_sakura_png = 'packages/gomiland/assets/images/trees/tree_sakura.png';

  static const String assets_images_trees_tree_sakura_bare_png = 'assets/images/trees/tree_sakura_bare.png';
  static const String gomiland$assets_images_trees_tree_sakura_bare_png = 'packages/gomiland/assets/images/trees/tree_sakura_bare.png';

  static const String assets_images_trees_tree_spiky_png = 'assets/images/trees/tree_spiky.png';
  static const String gomiland$assets_images_trees_tree_spiky_png = 'packages/gomiland/assets/images/trees/tree_spiky.png';

  static const String assets_images_trees_tree_willow_png = 'assets/images/trees/tree_willow.png';
  static const String gomiland$assets_images_trees_tree_willow_png = 'packages/gomiland/assets/images/trees/tree_willow.png';

  static const String assets_images_ui_a_button_png = 'assets/images/ui/a_button.png';
  static const String gomiland$assets_images_ui_a_button_png = 'packages/gomiland/assets/images/ui/a_button.png';

  static const String assets_images_ui_a_button_down_png = 'assets/images/ui/a_button_down.png';
  static const String gomiland$assets_images_ui_a_button_down_png = 'packages/gomiland/assets/images/ui/a_button_down.png';

  static const String assets_images_ui_bag_png = 'assets/images/ui/bag.png';
  static const String gomiland$assets_images_ui_bag_png = 'packages/gomiland/assets/images/ui/bag.png';

  static const String assets_images_ui_blue_button_png = 'assets/images/ui/blue_button.png';
  static const String gomiland$assets_images_ui_blue_button_png = 'packages/gomiland/assets/images/ui/blue_button.png';

  static const String assets_images_ui_cancel_png = 'assets/images/ui/cancel.png';
  static const String gomiland$assets_images_ui_cancel_png = 'packages/gomiland/assets/images/ui/cancel.png';

  static const String assets_images_ui_clock_png = 'assets/images/ui/clock.png';
  static const String gomiland$assets_images_ui_clock_png = 'packages/gomiland/assets/images/ui/clock.png';

  static const String assets_images_ui_dialogue_box_png = 'assets/images/ui/dialogue_box.png';
  static const String gomiland$assets_images_ui_dialogue_box_png = 'packages/gomiland/assets/images/ui/dialogue_box.png';

  static const String assets_images_ui_directional_knob_png = 'assets/images/ui/directional_knob.png';
  static const String gomiland$assets_images_ui_directional_knob_png = 'packages/gomiland/assets/images/ui/directional_knob.png';

  static const String assets_images_ui_directional_pad_png = 'assets/images/ui/directional_pad.png';
  static const String gomiland$assets_images_ui_directional_pad_png = 'packages/gomiland/assets/images/ui/directional_pad.png';

  static const String assets_images_ui_exit_button_png = 'assets/images/ui/exit_button.png';
  static const String gomiland$assets_images_ui_exit_button_png = 'packages/gomiland/assets/images/ui/exit_button.png';

  static const String assets_images_ui_exit_button_down_png = 'assets/images/ui/exit_button_down.png';
  static const String gomiland$assets_images_ui_exit_button_down_png = 'packages/gomiland/assets/images/ui/exit_button_down.png';

  static const String assets_images_ui_green_button_png = 'assets/images/ui/green_button.png';
  static const String gomiland$assets_images_ui_green_button_png = 'packages/gomiland/assets/images/ui/green_button.png';

  static const String assets_images_ui_info_box_png = 'assets/images/ui/info_box.png';
  static const String gomiland$assets_images_ui_info_box_png = 'packages/gomiland/assets/images/ui/info_box.png';

  static const String assets_images_ui_map_button_png = 'assets/images/ui/map_button.png';
  static const String gomiland$assets_images_ui_map_button_png = 'packages/gomiland/assets/images/ui/map_button.png';

  static const String assets_images_ui_menu_button_png = 'assets/images/ui/menu_button.png';
  static const String gomiland$assets_images_ui_menu_button_png = 'packages/gomiland/assets/images/ui/menu_button.png';

  static const String assets_images_ui_menu_button_down_png = 'assets/images/ui/menu_button_down.png';
  static const String gomiland$assets_images_ui_menu_button_down_png = 'packages/gomiland/assets/images/ui/menu_button_down.png';

  static const String assets_images_ui_red_button_png = 'assets/images/ui/red_button.png';
  static const String gomiland$assets_images_ui_red_button_png = 'packages/gomiland/assets/images/ui/red_button.png';

  static const String assets_tiles_bamboo_tsx = 'assets/tiles/bamboo.tsx';
  static const String gomiland$assets_tiles_bamboo_tsx = 'packages/gomiland/assets/tiles/bamboo.tsx';

  static const String assets_tiles_bins_tsx = 'assets/tiles/bins.tsx';
  static const String gomiland$assets_tiles_bins_tsx = 'packages/gomiland/assets/tiles/bins.tsx';

  static const String assets_tiles_bonsai_tsx = 'assets/tiles/bonsai.tsx';
  static const String gomiland$assets_tiles_bonsai_tsx = 'packages/gomiland/assets/tiles/bonsai.tsx';

  static const String assets_tiles_bridge_rail_tsx = 'assets/tiles/bridge_rail.tsx';
  static const String gomiland$assets_tiles_bridge_rail_tsx = 'packages/gomiland/assets/tiles/bridge_rail.tsx';

  static const String assets_tiles_buildings_tsx = 'assets/tiles/buildings.tsx';
  static const String gomiland$assets_tiles_buildings_tsx = 'packages/gomiland/assets/tiles/buildings.tsx';

  static const String assets_tiles_fence_tsx = 'assets/tiles/fence.tsx';
  static const String gomiland$assets_tiles_fence_tsx = 'packages/gomiland/assets/tiles/fence.tsx';

  static const String assets_tiles_grass_tsx = 'assets/tiles/grass.tsx';
  static const String gomiland$assets_tiles_grass_tsx = 'packages/gomiland/assets/tiles/grass.tsx';

  static const String assets_tiles_grass_barriers_tsx = 'assets/tiles/grass_barriers.tsx';
  static const String gomiland$assets_tiles_grass_barriers_tsx = 'packages/gomiland/assets/tiles/grass_barriers.tsx';

  static const String assets_tiles_hood_tmx = 'assets/tiles/hood.tmx';
  static const String gomiland$assets_tiles_hood_tmx = 'packages/gomiland/assets/tiles/hood.tmx';

  static const String assets_tiles_lights_tsx = 'assets/tiles/lights.tsx';
  static const String gomiland$assets_tiles_lights_tsx = 'packages/gomiland/assets/tiles/lights.tsx';

  static const String assets_tiles_objects_grass_tsx = 'assets/tiles/objects_grass.tsx';
  static const String gomiland$assets_tiles_objects_grass_tsx = 'packages/gomiland/assets/tiles/objects_grass.tsx';

  static const String assets_tiles_objects_street_tsx = 'assets/tiles/objects_street.tsx';
  static const String gomiland$assets_tiles_objects_street_tsx = 'packages/gomiland/assets/tiles/objects_street.tsx';

  static const String assets_tiles_park_tmx = 'assets/tiles/park.tmx';
  static const String gomiland$assets_tiles_park_tmx = 'packages/gomiland/assets/tiles/park.tmx';

  static const String assets_tiles_park_overlay_tsx = 'assets/tiles/park_overlay.tsx';
  static const String gomiland$assets_tiles_park_overlay_tsx = 'packages/gomiland/assets/tiles/park_overlay.tsx';

  static const String assets_tiles_pavement_tsx = 'assets/tiles/pavement.tsx';
  static const String gomiland$assets_tiles_pavement_tsx = 'packages/gomiland/assets/tiles/pavement.tsx';

  static const String assets_tiles_rock_wall_tsx = 'assets/tiles/rock_wall.tsx';
  static const String gomiland$assets_tiles_rock_wall_tsx = 'packages/gomiland/assets/tiles/rock_wall.tsx';

  static const String assets_tiles_room_tmx = 'assets/tiles/room.tmx';
  static const String gomiland$assets_tiles_room_tmx = 'packages/gomiland/assets/tiles/room.tmx';

  static const String assets_tiles_room_door_tsx = 'assets/tiles/room_door.tsx';
  static const String gomiland$assets_tiles_room_door_tsx = 'packages/gomiland/assets/tiles/room_door.tsx';

  static const String assets_tiles_room_tiles_tsx = 'assets/tiles/room_tiles.tsx';
  static const String gomiland$assets_tiles_room_tiles_tsx = 'packages/gomiland/assets/tiles/room_tiles.tsx';

  static const String assets_tiles_sand_tsx = 'assets/tiles/sand.tsx';
  static const String gomiland$assets_tiles_sand_tsx = 'packages/gomiland/assets/tiles/sand.tsx';

  static const String assets_tiles_street_overlays_tsx = 'assets/tiles/street_overlays.tsx';
  static const String gomiland$assets_tiles_street_overlays_tsx = 'packages/gomiland/assets/tiles/street_overlays.tsx';

  static const String assets_tiles_table_tsx = 'assets/tiles/table.tsx';
  static const String gomiland$assets_tiles_table_tsx = 'packages/gomiland/assets/tiles/table.tsx';

  static const String assets_tiles_track_fence_tsx = 'assets/tiles/track_fence.tsx';
  static const String gomiland$assets_tiles_track_fence_tsx = 'packages/gomiland/assets/tiles/track_fence.tsx';

  static const String assets_tiles_transitions_tsx = 'assets/tiles/transitions.tsx';
  static const String gomiland$assets_tiles_transitions_tsx = 'packages/gomiland/assets/tiles/transitions.tsx';

  static const String assets_tiles_trees_tsx = 'assets/tiles/trees.tsx';
  static const String gomiland$assets_tiles_trees_tsx = 'packages/gomiland/assets/tiles/trees.tsx';

  static const String assets_tiles_wall_tsx = 'assets/tiles/wall.tsx';
  static const String gomiland$assets_tiles_wall_tsx = 'packages/gomiland/assets/tiles/wall.tsx';

  static const String assets_tiles_wall_thick_tsx = 'assets/tiles/wall_thick.tsx';
  static const String gomiland$assets_tiles_wall_thick_tsx = 'packages/gomiland/assets/tiles/wall_thick.tsx';

  static const String assets_tiles_water_tsx = 'assets/tiles/water.tsx';
  static const String gomiland$assets_tiles_water_tsx = 'packages/gomiland/assets/tiles/water.tsx';

  static const String assets_tiles_waterfront_tsx = 'assets/tiles/waterfront.tsx';
  static const String gomiland$assets_tiles_waterfront_tsx = 'packages/gomiland/assets/tiles/waterfront.tsx';

  static const String assets_tiles_wood_base_tsx = 'assets/tiles/wood_base.tsx';
  static const String gomiland$assets_tiles_wood_base_tsx = 'packages/gomiland/assets/tiles/wood_base.tsx';

  static const String assets_yarn_anri_yarn = 'assets/yarn/anri.yarn';
  static const String gomiland$assets_yarn_anri_yarn = 'packages/gomiland/assets/yarn/anri.yarn';

  static const String assets_yarn_asimov_yarn = 'assets/yarn/asimov.yarn';
  static const String gomiland$assets_yarn_asimov_yarn = 'packages/gomiland/assets/yarn/asimov.yarn';

  static const String assets_yarn_brock_yarn = 'assets/yarn/brock.yarn';
  static const String gomiland$assets_yarn_brock_yarn = 'packages/gomiland/assets/yarn/brock.yarn';

  static const String assets_yarn_brocky_yarn = 'assets/yarn/brocky.yarn';
  static const String gomiland$assets_yarn_brocky_yarn = 'packages/gomiland/assets/yarn/brocky.yarn';

  static const String assets_yarn_florence_yarn = 'assets/yarn/florence.yarn';
  static const String gomiland$assets_yarn_florence_yarn = 'packages/gomiland/assets/yarn/florence.yarn';

  static const String assets_yarn_friend_yarn = 'assets/yarn/friend.yarn';
  static const String gomiland$assets_yarn_friend_yarn = 'packages/gomiland/assets/yarn/friend.yarn';

  static const String assets_yarn_gaia_yarn = 'assets/yarn/gaia.yarn';
  static const String gomiland$assets_yarn_gaia_yarn = 'packages/gomiland/assets/yarn/gaia.yarn';

  static const String assets_yarn_general_yarn = 'assets/yarn/general.yarn';
  static const String gomiland$assets_yarn_general_yarn = 'packages/gomiland/assets/yarn/general.yarn';

  static const String assets_yarn_hardy_yarn = 'assets/yarn/hardy.yarn';
  static const String gomiland$assets_yarn_hardy_yarn = 'packages/gomiland/assets/yarn/hardy.yarn';

  static const String assets_yarn_himiko_yarn = 'assets/yarn/himiko.yarn';
  static const String gomiland$assets_yarn_himiko_yarn = 'packages/gomiland/assets/yarn/himiko.yarn';

  static const String assets_yarn_hood_npcs_yarn = 'assets/yarn/hood_npcs.yarn';
  static const String gomiland$assets_yarn_hood_npcs_yarn = 'packages/gomiland/assets/yarn/hood_npcs.yarn';

  static const String assets_yarn_kushi_yarn = 'assets/yarn/kushi.yarn';
  static const String gomiland$assets_yarn_kushi_yarn = 'packages/gomiland/assets/yarn/kushi.yarn';

  static const String assets_yarn_manuka_yarn = 'assets/yarn/manuka.yarn';
  static const String gomiland$assets_yarn_manuka_yarn = 'packages/gomiland/assets/yarn/manuka.yarn';

  static const String assets_yarn_margret_yarn = 'assets/yarn/margret.yarn';
  static const String gomiland$assets_yarn_margret_yarn = 'packages/gomiland/assets/yarn/margret.yarn';

  static const String assets_yarn_moon_yarn = 'assets/yarn/moon.yarn';
  static const String gomiland$assets_yarn_moon_yarn = 'packages/gomiland/assets/yarn/moon.yarn';

  static const String assets_yarn_park_npcs_yarn = 'assets/yarn/park_npcs.yarn';
  static const String gomiland$assets_yarn_park_npcs_yarn = 'packages/gomiland/assets/yarn/park_npcs.yarn';

  static const String assets_yarn_peach_yarn = 'assets/yarn/peach.yarn';
  static const String gomiland$assets_yarn_peach_yarn = 'packages/gomiland/assets/yarn/peach.yarn';

  static const String assets_yarn_qian_bi_yarn = 'assets/yarn/qian_bi.yarn';
  static const String gomiland$assets_yarn_qian_bi_yarn = 'packages/gomiland/assets/yarn/qian_bi.yarn';

  static const String assets_yarn_ranger_yarn = 'assets/yarn/ranger.yarn';
  static const String gomiland$assets_yarn_ranger_yarn = 'packages/gomiland/assets/yarn/ranger.yarn';

  static const String assets_yarn_risa_yarn = 'assets/yarn/risa.yarn';
  static const String gomiland$assets_yarn_risa_yarn = 'packages/gomiland/assets/yarn/risa.yarn';

  static const String assets_yarn_rocky_yarn = 'assets/yarn/rocky.yarn';
  static const String gomiland$assets_yarn_rocky_yarn = 'packages/gomiland/assets/yarn/rocky.yarn';

  static const String assets_yarn_rubbish_error_yarn = 'assets/yarn/rubbish_error.yarn';
  static const String gomiland$assets_yarn_rubbish_error_yarn = 'packages/gomiland/assets/yarn/rubbish_error.yarn';

  static const String assets_yarn_scarlett_yarn = 'assets/yarn/scarlett.yarn';
  static const String gomiland$assets_yarn_scarlett_yarn = 'packages/gomiland/assets/yarn/scarlett.yarn';

  static const String assets_yarn_star_yarn = 'assets/yarn/star.yarn';
  static const String gomiland$assets_yarn_star_yarn = 'packages/gomiland/assets/yarn/star.yarn';

  static const String assets_yarn_stark_yarn = 'assets/yarn/stark.yarn';
  static const String gomiland$assets_yarn_stark_yarn = 'packages/gomiland/assets/yarn/stark.yarn';
}
