// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 22.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'gomiland';

  static const String assets_assets_images_buildings_entrance_png = 'assets/assets/images/buildings/entrance.png';
  static const String gomiland$assets_assets_images_buildings_entrance_png = 'packages/gomiland/assets/assets/images/buildings/entrance.png';

  static const String assets_assets_images_buildings_home_png = 'assets/assets/images/buildings/home.png';
  static const String gomiland$assets_assets_images_buildings_home_png = 'packages/gomiland/assets/assets/images/buildings/home.png';

  static const String assets_assets_images_logo_gomiland_simple_png = 'assets/assets/images/logo/gomiland_simple.png';
  static const String gomiland$assets_assets_images_logo_gomiland_simple_png = 'packages/gomiland/assets/assets/images/logo/gomiland_simple.png';

  static const String assets_assets_images_npcs_monk_idle_down_png = 'assets/assets/images/npcs/monk/idle_down.png';
  static const String gomiland$assets_assets_images_npcs_monk_idle_down_png = 'packages/gomiland/assets/assets/images/npcs/monk/idle_down.png';

  static const String assets_assets_images_npcs_monk_idle_left_png = 'assets/assets/images/npcs/monk/idle_left.png';
  static const String gomiland$assets_assets_images_npcs_monk_idle_left_png = 'packages/gomiland/assets/assets/images/npcs/monk/idle_left.png';

  static const String assets_assets_images_npcs_monk_idle_right_png = 'assets/assets/images/npcs/monk/idle_right.png';
  static const String gomiland$assets_assets_images_npcs_monk_idle_right_png = 'packages/gomiland/assets/assets/images/npcs/monk/idle_right.png';

  static const String assets_assets_images_npcs_monk_idle_up_png = 'assets/assets/images/npcs/monk/idle_up.png';
  static const String gomiland$assets_assets_images_npcs_monk_idle_up_png = 'packages/gomiland/assets/assets/images/npcs/monk/idle_up.png';

  static const String assets_assets_images_npcs_monk_move_down_png = 'assets/assets/images/npcs/monk/move_down.png';
  static const String gomiland$assets_assets_images_npcs_monk_move_down_png = 'packages/gomiland/assets/assets/images/npcs/monk/move_down.png';

  static const String assets_assets_images_npcs_monk_move_left_png = 'assets/assets/images/npcs/monk/move_left.png';
  static const String gomiland$assets_assets_images_npcs_monk_move_left_png = 'packages/gomiland/assets/assets/images/npcs/monk/move_left.png';

  static const String assets_assets_images_npcs_monk_move_right_png = 'assets/assets/images/npcs/monk/move_right.png';
  static const String gomiland$assets_assets_images_npcs_monk_move_right_png = 'packages/gomiland/assets/assets/images/npcs/monk/move_right.png';

  static const String assets_assets_images_npcs_monk_move_up_png = 'assets/assets/images/npcs/monk/move_up.png';
  static const String gomiland$assets_assets_images_npcs_monk_move_up_png = 'packages/gomiland/assets/assets/images/npcs/monk/move_up.png';

  static const String assets_assets_images_player_player_png = 'assets/assets/images/player/player.png';
  static const String gomiland$assets_assets_images_player_player_png = 'packages/gomiland/assets/assets/images/player/player.png';

  static const String assets_assets_images_spritesheets_coin_small_png = 'assets/assets/images/spritesheets/coin_small.png';
  static const String gomiland$assets_assets_images_spritesheets_coin_small_png = 'packages/gomiland/assets/assets/images/spritesheets/coin_small.png';

  static const String assets_audio_bgm_mountain_diary_mp3 = 'assets/audio/bgm/mountain_diary.mp3';
  static const String gomiland$assets_audio_bgm_mountain_diary_mp3 = 'packages/gomiland/assets/audio/bgm/mountain_diary.mp3';

  static const String assets_audio_bgm_olib_oil_mp3 = 'assets/audio/bgm/olib_oil.mp3';
  static const String gomiland$assets_audio_bgm_olib_oil_mp3 = 'packages/gomiland/assets/audio/bgm/olib_oil.mp3';

  static const String assets_audio_bgm_roomboi_mp3 = 'assets/audio/bgm/roomboi.mp3';
  static const String gomiland$assets_audio_bgm_roomboi_mp3 = 'packages/gomiland/assets/audio/bgm/roomboi.mp3';

  static const String assets_audio_bgm_scenic_stroll_mp3 = 'assets/audio/bgm/scenic_stroll.mp3';
  static const String gomiland$assets_audio_bgm_scenic_stroll_mp3 = 'packages/gomiland/assets/audio/bgm/scenic_stroll.mp3';

  static const String assets_audio_bgm_wumwob_squarewave_mp3 = 'assets/audio/bgm/wumwob_squarewave.mp3';
  static const String gomiland$assets_audio_bgm_wumwob_squarewave_mp3 = 'packages/gomiland/assets/audio/bgm/wumwob_squarewave.mp3';

  static const String assets_audio_sfx_correct_mp3 = 'assets/audio/sfx/correct.mp3';
  static const String gomiland$assets_audio_sfx_correct_mp3 = 'packages/gomiland/assets/audio/sfx/correct.mp3';

  static const String assets_audio_sfx_incorrect_mp3 = 'assets/audio/sfx/incorrect.mp3';
  static const String gomiland$assets_audio_sfx_incorrect_mp3 = 'packages/gomiland/assets/audio/sfx/incorrect.mp3';

  static const String assets_audio_sfx_next_mp3 = 'assets/audio/sfx/next.mp3';
  static const String gomiland$assets_audio_sfx_next_mp3 = 'packages/gomiland/assets/audio/sfx/next.mp3';

  static const String assets_audio_sfx_pickup_mp3 = 'assets/audio/sfx/pickup.mp3';
  static const String gomiland$assets_audio_sfx_pickup_mp3 = 'packages/gomiland/assets/audio/sfx/pickup.mp3';
}
